package com.quckapp.auth.domain.entity;

/**
 * Types of login anomalies
 */
public enum AnomalyType {
    NEW_DEVICE,
    NEW_LOCATION,
    NEW_COUNTRY,
    IMPOSSIBLE_TRAVEL,
    MULTIPLE_FAILED_ATTEMPTS,
    BRUTE_FORCE_DETECTED,
    VPN_DETECTED,
    TOR_DETECTED,
    PROXY_DETECTED,
    SUSPICIOUS_USER_AGENT,
    UNUSUAL_TIME,
    HIGH_RISK_IP,
    CREDENTIAL_STUFFING,
    BOT_DETECTED,
    SESSION_HIJACKING,
    CONCURRENT_SESSIONS_EXCEEDED,
    IP_REPUTATION_LOW,
    DEVICE_FINGERPRINT_MISMATCH
}
